chore(*): Export base classes and mixins.
IgniteUI/igniteui-webcomponents pull request #109
Opened 2021-11-04 11:12 UTC by gedinakova

Closes #107

2021-11-04 12:23 UTC, DiyanDimitrov requested changes
Export `IgcCalendarResourceStrings` interface.

2021-11-04 12:23 UTC, DiyanDimitrov commented on src/index.ts
> +  Calendar,
These are used only internally by the calendar.
```suggestion
  DateRangeDescriptor,
  DateRangeType,
```

2021-11-04 12:23 UTC, DiyanDimitrov commented on src/index.ts
> +export { IgcDaysViewEventMap } from './components/calendar/days-view/days-view';
Days-view is not a public component.
```suggestion
```

2021-11-04 14:53 UTC, DiyanDimitrov approved these changes

2021-11-05 13:27 UTC, rkaraivanov approved these changes

2021-11-05 13:28 UTC, merged