feat(calendar): add styles for disabled and special dates
IgniteUI/igniteui-webcomponents pull request #110
Opened 2021-11-04 12:33 UTC by desig9stein

closes #98

2021-11-04 12:35 UTC, simeonoff requested changes

2021-11-04 12:35 UTC, simeonoff commented on src/components/calendar/calendar.material.scss
> +$calendar-bacground: color(surface);
```suggestion
$calendar-background: color(surface);
```

2021-11-04 12:35 UTC, simeonoff commented on src/components/calendar/calendar.material.scss
> +    background: $calendar-bacground;
```suggestion
    background: $calendar-background;
```

2021-11-04 12:52 UTC, simeonoff submitted a review, later dismissed

2021-11-04 13:01 UTC, StefanIvanov approved these changes

2021-11-04 13:44 UTC, desig9stein commented
@DiyanDimitrov @StefanIvanov  after fixing the styling I saw that I am able to navigate over the disabled dates using the keyboard. Is this on purpose? I am asking because I saw that in igniteui for angular this is not possible.

2021-11-04 13:46 UTC, StefanIvanov approved these changes

2021-11-04 13:46 UTC, StefanIvanov commented
> @DiyanDimitrov @StefanIvanov after fixing the styling I saw that I am able to navigate over the disabled dates using the keyboard. Is this on purpose? I am asking because I saw that in igniteui for angular this is not possible.

This looks like a bug to me, disabled dates should not be possible to navigate to by any means because they are disabled :)

2021-11-04 14:42 UTC, DiyanDimitrov commented
> > @DiyanDimitrov @StefanIvanov after fixing the styling I saw that I am able to navigate over the disabled dates using the keyboard. Is this on purpose? I am asking because I saw that in igniteui for angular this is not possible.
> 
> This looks like a bug to me, disabled dates should not be possible to navigate to by any means because they are disabled :)

Actually this is intended behavior in the IgcCalendar. The disabled dates can be navigated using the keyboard, but cannot be selected. When using a screen reader while navigating the disabled dates you will be notified that this date is disabled. If the disabled dates are not focusable we will just skip them without notifying the screen reader why.

2021-11-04 15:50 UTC, DiyanDimitrov commented
> > > > @DiyanDimitrov @StefanIvanov after fixing the styling I saw that I am able to navigate over the disabled dates using the keyboard. Is this on purpose? I am asking because I saw that in igniteui for angular this is not possible.
> > > 
> > > 
> > > This looks like a bug to me, disabled dates should not be possible to navigate to by any means because they are disabled :)
> > 
> > 
> > Actually this is intended behavior in the IgcCalendar. The disabled dates can be navigated using the keyboard, but cannot be selected. When using a screen reader while navigating the disabled dates you will be notified that this date is disabled. If the disabled dates are not focusable we will just skip them without notifying the screen reader why.
> 
> ОК I didn't see that use case and it is a valid one, but then how about Angular, should we suggest this as an enhancement there?

Yes, we could implement it with all other design changes that we have made in the IgcCalendar.

2021-11-05 08:20 UTC, simeonoff submitted a review, later dismissed

2021-11-05 16:25 UTC, DiyanDimitrov commented
Clicking on outside days is broken, we should switch the month to previous/next month when clicking leading/trailing days.

2021-11-05 16:38 UTC, DiyanDimitrov commented
> Clicking on outside days is broken, we should switch the month to previous/next month when clicking leading/trailing days.

It was an issue with the parts that we apply. I have fixed it.

2021-11-05 16:39 UTC, DiyanDimitrov approved these changes

2021-11-05 16:43 UTC, merged