chore(*): add contributing guide
IgniteUI/igniteui-webcomponents pull request #211
Opened 2022-01-18 13:21 UTC by DiyanDimitrov

2022-01-20 08:11 UTC, gedinakova requested changes

2022-01-20 08:11 UTC, gedinakova commented on .github/CONTRIBUTING.md
> +export export default class IgcSomethingComponent extends LitElement {
```suggestion
export default class IgcSomethingComponent extends LitElement {
```

2022-01-20 12:01 UTC, gedinakova approved these changes

2022-01-24 09:00 UTC, simeonoff approved these changes

2022-01-24 09:02 UTC, rkaraivanov approved these changes

2022-01-24 09:04 UTC, merged