feat(toast): add toast component
IgniteUI/igniteui-webcomponents pull request #216
Opened 2022-01-20 08:58 UTC by didimmova

2022-03-10 10:28 UTC, StefanIvanov approved these changes

2022-03-10 15:30 UTC, StefanIvanov submitted a review, later dismissed

2022-03-11 07:49 UTC, simeonoff requested changes

2022-03-11 07:49 UTC, simeonoff commented on src/components/toast/themes/toast.material.scss
> +@use '../../../styles/utilities' as *;
Scrap this file altogether.

2022-03-11 09:13 UTC, merged