chore(*): roadmap-update-11-mar-22
IgniteUI/igniteui-webcomponents pull request #288
Opened 2022-03-11 13:24 UTC by radomirchev

all tags and labels are set

2022-03-11 13:30 UTC, ChronosSF requested changes

2022-03-11 13:30 UTC, ChronosSF commented on ROADMAP.md
> +3. Slider component [#181](https://github.com/IgniteUI/igniteui-webcomponents/issues/181)
Slider is already released.

2022-03-11 13:30 UTC, ChronosSF commented on ROADMAP.md
>  7. Snackbar component [#182](https://github.com/IgniteUI/igniteui-webcomponents/issues/182)
Snackbar is getting released next week and can be moved under Milestone 2

2022-03-14 13:59 UTC, radomirchev reviewed
All comments are addressed

2022-03-14 14:00 UTC, ChronosSF approved these changes

2022-03-31 07:59 UTC, merged