feat(card): Card implementation
IgniteUI/igniteui-webcomponents pull request #41
Opened 2021-08-11 14:05 UTC by astaev

Initial commit for card implementation

2021-09-07 08:20 UTC, simeonoff reviewed
The padding between the individual card components should be set by the card theme, not each individual component. This will allow for greater control and composability.

2021-09-07 08:20 UTC, simeonoff commented on src/components/card/card.media.material.scss
> +    overflow: hidden;
Make this flex and align items in the middle.

2021-09-09 08:01 UTC, desig9stein requested changes

2021-09-10 07:41 UTC, simeonoff approved these changes

2021-09-10 07:46 UTC, desig9stein approved these changes

2021-09-10 07:53 UTC, merged