fix(snackbar): differences between Ignite UI for Angular and WC
IgniteUI/igniteui-webcomponents pull request #424
Opened 2022-06-24 08:45 UTC by SisIvanova

Closes #421

2022-06-27 14:53 UTC, simeonoff submitted a review, later dismissed

2022-06-30 07:53 UTC, YoannaIvanova commented
@SisIvanova 
The snackbar height in Bootstrap in Angular is 48px, but in WC, it is 52px. It should be 48px too.

2022-06-30 07:54 UTC, YoannaIvanova requested changes
@SisIvanova 
The snackbar height in Bootstrap in Angular is 48px, but in WC, it is 52px. It should be 48px too.

2022-07-01 12:25 UTC, simeonoff commented
> @SisIvanova The snackbar height in Bootstrap in Angular is 48px, but in WC, it is 52px. It should be 48px too.

Should be fine now.

2022-07-01 12:35 UTC, simeonoff approved these changes

2022-07-01 12:48 UTC, YoannaIvanova approved these changes

2022-07-01 12:49 UTC, merged