Add Input Component
IgniteUI/igniteui-webcomponents pull request #44
Opened 2021-08-13 14:23 UTC by simeonoff

2021-09-09 14:02 UTC, SisIvanova approved these changes

2021-09-09 14:02 UTC, SisIvanova commented on src/components/input/input.material.scss
> +        padding-inline-start: 4px;
```suggestion
        padding-inline-start: rem(4px);
```

2021-09-09 14:02 UTC, SisIvanova commented on src/components/input/input.material.scss
> +    [part='end'], {
```suggestion
    [part='end'] {
```

2021-09-10 06:40 UTC, desig9stein submitted a review, later dismissed

2021-09-13 07:38 UTC, rkaraivanov requested changes
LGTM except for two points:

1. API documentation - Document the public API of the component. Also the `handle${foo}` and `render${part}` methods could be with access level `protected`.
2. What about `focus()` and `blur()` methods? We expose those for the other input types (checkbox, radio). I think they should be present here as well

2021-09-13 07:38 UTC, rkaraivanov commented on src/components/input/input.ts
> +export interface IgcRadioEventMap {
I guess you meant `InputEventMap`

2021-09-14 06:44 UTC, SisIvanova commented on src/components/input/input.ts
> +  /** The inputmode attribute of the control. */
input mode

2021-09-14 06:45 UTC, SisIvanova commented on src/components/input/input.ts
> +  /** Checks for validity of the control and shows the browser message if it invalid. */
its

2021-09-14 06:51 UTC, SisIvanova approved these changes

2021-09-14 09:03 UTC, SisIvanova approved these changes

2021-09-15 11:07 UTC, rkaraivanov approved these changes

2021-09-15 11:44 UTC, DiyanDimitrov approved these changes

2021-09-15 11:46 UTC, merged