fix(toast): adding alert role for toast
IgniteUI/igniteui-webcomponents pull request #492
Opened 2022-08-25 13:42 UTC by ChronosSF

Closes #479

2022-08-29 05:53 UTC, rkaraivanov requested changes

2022-08-29 05:53 UTC, rkaraivanov commented on src/components/toast/toast.ts
> +  }
You should move this to the connectedCallback hook.
As per the [specification](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance):

> The element must not gain any attributes or children, as this violates the expectations of consumers who use the [createElement](https://dom.spec.whatwg.org/#dom-document-createelement) or [createElementNS](https://dom.spec.whatwg.org/#dom-document-createelementns) methods.

2022-08-29 06:42 UTC, desig9stein commented
@ChronosSF The reader on mac does not read anything with just the role, however, adding `aria-live="polite"` seems to fix the problem. 

We use the same approach in Angular.

[igx toast](https://www.infragistics.com/products/ignite-ui-angular/angular/components/toast#show-toast)
[aria-live](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live)

2022-08-29 11:24 UTC, ChronosSF commented
Sadly, providing any aria-live seems to completely kill off the read out from Windows Narrator, but that seems to be the case with angular too. I guess having it read on Mac is better as we kinda go in the way of using nvda as baseline.

2022-08-30 08:01 UTC, rkaraivanov approved these changes

2022-08-30 08:02 UTC, merged