chore(8): readme-toc-update
IgniteUI/igniteui-webcomponents pull request #514
Opened 2022-09-26 12:59 UTC by radomirchev

Update the readme table with release versions with changed sorting form ascending to descending

2022-09-26 13:19 UTC, kdinev requested changes
Please also update with the components in `3.4.0`

2022-09-28 07:22 UTC, kdinev commented
@radomirchev Reminder about this.

2022-09-28 08:32 UTC, radomirchev reviewed
3.4.0 components are added

2022-09-28 08:44 UTC, kdinev approved these changes

2022-09-28 08:44 UTC, merged