Add Form Component
IgniteUI/igniteui-webcomponents pull request #53
Opened 2021-08-27 16:12 UTC by igdmdimitrov

Closes #35

2021-09-01 15:35 UTC, DiyanDimitrov requested changes

2021-09-01 15:35 UTC, DiyanDimitrov commented on src/components/form/form.ts
> +        formData.append(element.name, element.value);
We have to handle `select` element with a `multiple` attribute in a special way.

2021-09-01 15:35 UTC, DiyanDimitrov commented on src/components/form/form.ts
> +        (this._controlsWithChecked.includes(element.tagName.toLowerCase()) &&
We have to skip disabled elements.

2021-09-01 15:35 UTC, DiyanDimitrov commented on src/components/form/form.ts
> +      this.emitEvent('igcSubmit', { detail: formData });
Shouldn't we just call the submit method?

2021-09-13 13:28 UTC, zhosti commented on stories/form.stories.ts
> +// import { ifDefined } from 'lit-html/directives/if-defined';
Remove the commented code

2021-09-15 08:05 UTC, zhosti approved these changes

2021-09-15 12:21 UTC, DiyanDimitrov requested changes

2021-09-15 12:21 UTC, DiyanDimitrov commented on src/components/form/form.ts
> +            formData.append(element.name, option.text);
We should use the `option.value`.
```suggestion
            formData.append(element.name, option.value);
```

2021-09-15 13:13 UTC, DiyanDimitrov commented on src/components/form/form.ts
> +    const isValid = this.reportValidity();
`reportValidity` should not be called if `novalidate` is true.

2021-09-16 08:59 UTC, DiyanDimitrov commented on src/components/form/form.ts
> +  private _controlsWithValue = ['input', 'textarea'];
Add `igc-input` here. Also add `igc-input` and `igc-checkbox` to the story.

2021-09-16 14:45 UTC, DiyanDimitrov requested changes

2021-09-16 14:45 UTC, DiyanDimitrov commented on src/components/form/form.ts
> +        element.value = element.defaultValue;
For consistency we could use `getAttribute` for all value controls.
```suggestion
      } else if (this._controlsWithValue.includes(tagName)) {
        element.value = element.getAttribute('value');
```

2021-09-16 16:48 UTC, DiyanDimitrov commented on src/components/form/form.ts
> +        element.value = element.defaultValue;
Aaand we broke the textarea... You could revert this change :)

2021-09-17 09:31 UTC, gedinakova requested changes

2021-09-17 09:31 UTC, gedinakova commented on src/components/form/form.ts
> +  /** Specifies if the form should not to be validated on submit. */
Let's change this to something like "Specifies if form data validation should be skipped on submit."

2021-09-17 12:53 UTC, gedinakova approved these changes

2021-09-17 12:55 UTC, DiyanDimitrov approved these changes

2021-09-17 13:48 UTC, zhosti approved these changes

2021-09-21 06:47 UTC, merged