fix(calendar): navigate to the date set as value initially
IgniteUI/igniteui-webcomponents pull request #615
Opened 2023-01-12 13:29 UTC by ddaribo

Closes #436

2023-01-12 13:41 UTC, wnvko commented on src/components/calendar/common/calendar-base.ts
> +      this.activeDate = this.value ? this.value : new Date();
you can simplify this with [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing)

2023-01-12 13:41 UTC, wnvko approved these changes

2023-01-12 14:06 UTC, wnvko approved these changes

2023-03-08 08:39 UTC, rkaraivanov commented
@ddaribo 
[Here](https://github.com/IgniteUI/igniteui-webcomponents/wiki/Calendar-Specification#active-date-with-selection) is the updated behavior of how active date and set values should interact in the calendar.

2023-03-08 08:57 UTC, wnvko reviewed
Issue updated as per the new specification.
Please update component to follow the spec and add tests for each active date related scenario described in the tests.

2023-03-08 08:59 UTC, wnvko requested changes
Issue updated as per the new specification.
Please update component to follow the spec and add tests for each active date related scenario described in the spec.

2023-03-29 08:52 UTC, wnvko approved these changes

2023-03-29 09:40 UTC, merged