docs(list): add api docs #61
IgniteUI/igniteui-webcomponents pull request #62
Opened 2021-09-14 14:51 UTC by zhosti

Closes #61

2021-09-15 11:55 UTC, igdmdimitrov approved these changes

2021-09-16 08:36 UTC, gedinakova requested changes

2021-09-16 08:36 UTC, gedinakova commented on src/components/list/list-header.ts
> + * Header component for list items.
Isn't this just a header list item. "Header component for list items" kind of has a different meaning.

2021-09-16 08:36 UTC, gedinakova commented on src/components/list/list-item.ts
> + * @slot - Renders a custom content.
No 'a' before content.

2021-09-16 08:36 UTC, gedinakova commented on src/components/list/list-item.ts
> + * @slot start - Renders the content before the title and subtitle.
No 'the' before content.

2021-09-16 08:36 UTC, gedinakova commented on src/components/list/list-item.ts
> + * @slot end - Renders the content after the title and subtitle.
No 'the' before content. It rather "Renders content after all other content."

2021-09-16 08:36 UTC, gedinakova commented on src/components/list/list-item.ts
> + * @csspart content - The header and custom template container.
Probably "content" instead of "template"?

2021-09-16 08:36 UTC, gedinakova commented on src/components/list/list-item.ts
> + * @csspart title - The title wrapper.
"Container" instead of "wrapper".

2021-09-16 08:36 UTC, gedinakova commented on src/components/list/list-item.ts
> + * @csspart subtitle - The subtitle wrapper.
Same as above.

2021-09-16 10:05 UTC, onlyexeption commented on src/components/list/list-item.ts
> + * intended for row items in the list component.
I think intended is unnecessary here

2021-09-16 12:26 UTC, onlyexeption submitted a review, later dismissed

2021-09-17 09:26 UTC, gedinakova requested changes

2021-09-17 09:26 UTC, gedinakova commented on src/components/list/list-header.ts
> + * @slot - Renders a header for the list items.
Let's change this to "Renders header list item's content.".

2021-09-20 09:15 UTC, gedinakova approved these changes

2021-09-23 07:58 UTC, merged