feat(combo): add simplified option
IgniteUI/igniteui-webcomponents pull request #622
Opened 2023-01-17 11:22 UTC by simeonoff

2023-01-19 11:31 UTC, SisIvanova commented
We should remove the text highlight when the combo is disabled


https://user-images.githubusercontent.com/59446295/213431568-9df458fa-202f-4b1c-83d0-92306b58306b.mov

2023-01-24 10:22 UTC, SisIvanova approved these changes

2023-01-25 08:23 UTC, rkaraivanov requested changes
LGTM

2023-01-25 08:23 UTC, rkaraivanov commented on src/components/combo/combo-item.ts
> +  @property({ attribute: 'hide-checkbox', type: Boolean, reflect: true })
```suggestion
  @property({ attribute: false, type: Boolean })
```
Unless there is a styling need, I don't see a reason to have a reflecting attribute here

2023-01-25 08:23 UTC, rkaraivanov commented on src/components/combo/combo-item.ts
> +          ?hidden=${this.hideCheckbox}
Do we really need to render a hidden checkbox when single selection is enabled?

2023-01-25 09:40 UTC, rkaraivanov approved these changes

2023-01-25 09:54 UTC, SisIvanova approved these changes

2023-01-25 10:36 UTC, merged