Add Icon Button Component
IgniteUI/igniteui-webcomponents pull request #63
Opened 2021-09-15 10:36 UTC by simeonoff

Closes #46

2021-09-17 12:54 UTC, SisIvanova commented on src/components/button/icon-button.indigo.scss
> +            box-shadow .15s ease-in-out,
```suggestion
           box-shadow .15s ease-in-out,
```

2021-09-17 12:54 UTC, SisIvanova commented on src/components/button/icon-button.indigo.scss
> +            background .15s ease-in-out;
```suggestion
           background .15s ease-in-out;
```

2021-09-17 12:54 UTC, SisIvanova commented on src/components/button/icon-button.material.scss
> +    outline-style : none;
```suggestion
    outline-style: none;
```

2021-09-17 12:54 UTC, SisIvanova commented on src/components/button/icon-button.spec.ts
> +      <igc-link-button>`
```suggestion
      </igc-icon-button>`
```

2021-09-17 12:54 UTC, SisIvanova commented on stories/card.stories.ts
> +          <igc-icon-button slot="end" name="home"></igc-icon>
```suggestion
          <igc-icon-button slot="end" name="home"></igc-icon-button>
```

2021-09-17 13:02 UTC, SisIvanova submitted a review, later dismissed

2021-09-27 13:08 UTC, gedinakova requested changes
Please, add the appropriate access modifiers to all API members.

2021-09-27 13:08 UTC, gedinakova commented on src/components/button/icon-button.ts
> +  protected renderIcon() {
`private` instead of `protected`?

2021-09-27 13:08 UTC, gedinakova commented on src/components/button/icon-button.ts
> +  /** The href attribute of the icon. */
From here on, the comments should probably mention `icon button` instead of just `icon`.

2021-09-27 13:10 UTC, gedinakova requested changes

2021-09-27 13:10 UTC, gedinakova commented on src/components/button/icon-button.ts
> +import { html } from 'lit';
Add access modifiers to all API members.

2021-09-28 06:22 UTC, gedinakova approved these changes

2021-09-28 14:44 UTC, merged