Add slider component
IgniteUI/igniteui-webcomponents pull request #77
Opened 2021-09-28 13:10 UTC by mtsvyatkova

Closes #39

2021-10-14 14:11 UTC, rkaraivanov commented
@mtsvyatkova 
Ok, can we take a different approach for slider component.

Can we:
* Separate the thumb logic and implementation as a separate component
* Make use of the `@watch` decorator we have in the repository instead of calling `requestUpdate`. As
a bonus it can wait for the first update paint.
* The implementation is very "Angularish" which is maybe not the correct approach in this case.

Maybe we can get together in a session and discuss the points above

2022-01-04 12:32 UTC, rkaraivanov requested changes
LGTM with some suggestions.

Also, add an entry into the changelog

2022-01-04 12:32 UTC, rkaraivanov commented on src/components/slider/slider-base.ts
> +    for (let i = 0; i < this.totalTickCount(); i++) {
```suggestion
    for (let i = 0, totalCount = totalTickCount(); i < totalCount; i++) {
```
A little nitpick but I don't think we need to call the method on each iteration. Or maybe cache the tick count and update it when the ticks properties change.

2022-01-05 10:04 UTC, DiyanDimitrov commented
@gmurray81, Could you please take a look at the public API of the slider components and let us know if it will work ok for Blazor? I have some concerns for the range slider.  We have `lower` and `upper` value properties and a single `igcInput/igcChange` event is emitted when any of the two values is changed. Is that going to work ok for the Blazor bindings?

2022-01-05 12:03 UTC, gmurray81 commented
Thanks for the heads up @DiyanDimitrov will look into it soon.

2022-01-14 09:18 UTC, gedinakova approved these changes

2022-01-14 11:29 UTC, DiyanDimitrov commented
> Thanks for the heads up @DiyanDimitrov will look into it soon.

@gmurray81, Did you get a chance to look into this?

2022-01-14 14:01 UTC, gmurray81 commented
@DiyanDimitrov I think we should be able to make that work as long as the args have the values in them

2022-01-14 14:01 UTC, gmurray81 commented
but I'll probably need to adjust something in the auto gen, at a guess

2022-01-17 09:31 UTC, rkaraivanov approved these changes

2022-01-17 12:28 UTC, simeonoff approved these changes

2022-01-17 12:35 UTC, merged