feat: Added text area component
IgniteUI/igniteui-webcomponents pull request #773
Opened 2023-05-26 05:26 UTC by rkaraivanov

Closes #764

2023-06-27 08:53 UTC, rkaraivanov commented
@SisIvanova 

I thought that sizing was done through CSS variables. Can you remove the SizableMixin and style it based on the CSS variable?

2023-06-28 07:11 UTC, SisIvanova commented on src/components/textarea/textarea.ts
> +      <div part="helper-text" .hidden=${this.helperText.length < 0}>
```suggestion
      <div part="helper-text" .hidden=${this.helperText.length < 1}>
```

2023-06-28 07:11 UTC, SisIvanova commented on src/components/textarea/textarea.ts
> +        ${this.renderInput()}
Can we move the notch before the input? Otherwise, the notch is displayed over the textarea therefore the text can't be scrolled.

2023-10-02 09:47 UTC, simeonoff requested changes
The styles need some minor changes.

2023-10-02 09:47 UTC, simeonoff commented on src/components/textarea/themes/light/textarea.base.scss
> +    'compact': 22px
```suggestion
    'large': rem(16px),
    'medium': rem(19px),
    'small': rem(22px)
```

2023-10-02 09:47 UTC, simeonoff commented on src/components/textarea/themes/light/textarea.base.scss
> +        rem(82px, map.get($base-scale-size, 'comfortable'))
```suggestion
        rem(82px, map.get($base-scale-size, 'small')),
        rem(82px, map.get($base-scale-size, 'medium')),
        rem(82px, map.get($base-scale-size, 'large'))
```

2023-10-02 09:47 UTC, simeonoff commented on src/components/textarea/themes/light/textarea.base.scss
> +    padding-inline: pad-inline(8px, 12px, 16px);
Use rem units here.

2023-10-02 09:47 UTC, simeonoff commented on src/components/textarea/themes/light/textarea.bootstrap.scss
> +    padding-inline: pad-inline(8px, 12px, 16px);
Use rem units here.

2023-10-02 09:47 UTC, simeonoff commented on src/components/textarea/themes/light/textarea.bootstrap.scss
> +    font-size: pad(14px, 16px, 20px);
Use rem units here.

2023-10-02 11:01 UTC, simeonoff commented
@desig9stein can you validate the implemented component against angular for differences?

2023-10-02 12:19 UTC, desig9stein commented
@SisIvanova I spotted a few things.
1. There are colors in the `textarea.base.scss`. base files should not have colors.
2. Color transitions in all themes except fluent are different from angular.
3. Material box type in angular has animation on focus, the blue line is animated from the center to the sides
4. No need to import @use 'sass:map'; if it's not used In the file.

2023-10-06 12:17 UTC, simeonoff approved these changes

2023-10-06 12:17 UTC, merged