refactor(dropdown): use colors from schemas
IgniteUI/igniteui-webcomponents pull request #835
Opened 2023-07-19 13:52 UTC by desig9stein

Closes #828

2023-07-20 12:39 UTC, simeonoff requested changes

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/dropdown.bootstrap.scss
> +    background: color(surface, 500);
Shouldn't this be consumed from the schema file?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/dropdown.bootstrap.scss
> +    border: rem(1px) solid var(--border-color, color(gray, 300));
How about the border-color here?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/dropdown.fluent.scss
> +    background: color(surface, 500);
Schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/dropdown.indigo.scss
> +    background: color(surface, 500);
Schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/dropdown.material.scss
> +    background: color(surface, 500);
Schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/group/dropdown-group.bootstrap.scss
> +        color: color(secondary, 500);
Shouldn't this come from the schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/group/dropdown-group.fluent.scss
> +        color: color(secondary, 500);
Shouldn't this come from the schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/group/dropdown-group.fluent.scss
> +        padding: pad(2px, 4px, 8px);
```suggestion
        padding: pad(rem(2px), rem(4px), (8px));
```

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/group/dropdown-group.indigo.scss
> +        color: color(secondary, 500);
Shouldn't this come from the schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/group/dropdown-group.material.scss
> +        color: color(secondary, 500);
Shouldn't this come from the schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/header/dropdown-header.bootstrap.scss
> +    color: color(gray, 700);
Shouldn't this come from the schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/header/dropdown-header.bootstrap.scss
> +    padding-block: pad-block(2px, 4px, 8px);
```suggestion
    padding-inline: pad-inline(rem(4px), rem(8px), rem(16px));
    padding-block: pad-block(rem(2px), rem(4px), rem(8px));
```

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/header/dropdown-header.fluent.scss
> +    color: var(--header-color, color(secondary, 500));
Shouldn't this come from the schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/header/dropdown-header.fluent.scss
> +    padding: pad(2px, 4px, 8px);
```suggestion
    padding: pad(rem(2px), rem(4px), rem(8px));
```

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/header/dropdown-header.indigo.scss
> +    color: var(--header-color, color(secondary, 500));
Shouldn't this come from the schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/header/dropdown-header.indigo.scss
> +    padding-block: pad-block(2px, 4px, 8px);
```suggestion
    padding-inline: pad-inline(rem(4px), rem(8px), rem(16px));
    padding-block: pad-block(rem(2px), rem(4px), rem(8px));
```

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/header/dropdown-header.material.scss
> +    color: var(--header-color, color(secondary, 500));
Shouldn't this come from the schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/header/dropdown-header.material.scss
> +    padding-block: pad-block(2px, 4px, 8px);
```suggestion
    padding-inline: pad-inline(rem(4px), rem(8px), rem(16px));
    padding-block: pad-block(rem(2px), rem(4px), rem(8px));
```

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/item/dropdown-item.base.scss
> +    padding-block: pad-block(2px, 4px, 8px);
```suggestion
    padding-inline: pad-inline(rem(6px), rem(12px), rem(24px));
    padding-block: pad-block(rem(2px), rem(4px), rem(8px));
```

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/item/dropdown-item.base.scss
> +    margin-inline-end: pad(16px);
```suggestion
    margin-inline-end: pad(rem(16px));
```

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/item/dropdown-item.base.scss
> +    margin-inline-start: pad(16px);
```suggestion
    margin-inline-start: pad(rem(16px));
```

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/item/dropdown-item.bootstrap.scss
> +$hover-item-color: var(--hover-item-color, contrast-color(gray, 100)) !default;
Shouldn't this come from the schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/item/dropdown-item.fluent.scss
> +$selected-item-color: var(--selected-item-color, contrast-color(gray, 200)) !default;
Shouldn't this come from the schema?

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/item/dropdown-item.fluent.scss
> +    padding: pad(2px, 4px, 8px);
```suggestion
    padding: pad(rem(2px), rem(4px), rem(8px));
```

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/group/dropdown-group.base.scss
>          padding-inline: pad-inline(4px, 8px, 16px);
```suggestion
        padding-inline: pad-inline(rem(4px), rem(8px), rem(16px));
```

2023-07-20 12:39 UTC, simeonoff commented on src/components/dropdown/themes/light/group/dropdown-group.base.scss
>          padding-block: pad-block(2px, 4px, 8px);
```suggestion
        padding-block: pad-block(rem(2px), rem(4px), rem(8px));
```

2023-07-21 11:12 UTC, desig9stein commented
@simeonoff I need to implement the dark themes as well

2023-07-21 11:15 UTC, simeonoff approved these changes

2023-07-21 11:53 UTC, simeonoff approved these changes

2023-07-21 11:53 UTC, merged